# Problem:
# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with $1$ and $2$, the first $10$ terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89 ... 
# By considering the terms in the Fibonacci sequence whose values do not 
# exceed four million, find the sum of the even-valued terms.
  
  fib<-c(1,2,3)
  for (i in 4:1000) {
    fib[i]<-fib[i-1]+fib[i-2]
    if(fib[i]>4000000){
      fib[i]<-NA
      fib<-na.omit(fib)
      break
    }
  }

  j<-1
  fib.even<-c()
  for (i in 1:length(fib)) {
    if(trunc(fib[i]/2)==fib[i]/2){
      fib.even[j]<-fib[i]
      j<-j+1
    }
  }
  
  sum(fib.even)
  